about:
  title: Postview
  subtitle: Post your articles
  author: You
  email: you@example.com
  url: http://you.example.com/
directories:
  posts: posts
  archive: posts/archive
  drafts: posts/drafts
paths:
  posts: posts
  tags: tags
  archive: archive
  search: search
  about: about

